title: Jekyll Travis gh-pages
description: Demo of jekyll + travis + gh-pages
baseurl: "/jekyll-travis-gh-pages"

# Build settings
markdown: kramdown

collections:
  animals:
    output: true

gems:
  - octopress-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  